version: "3"

tasks:
  noga_csv:
    desc: "Convert noga's data from xlsx to csv"
    status:
      - test -f data/noga.csv
    cmds:
      - "uv run -m noga.data noga_csv"

  ims_csv:
    desc: "Convert IMS data from xlsx to csv"
    status:
      - test -f data/ims.csv
    cmds:
      - "uv run -m noga.data ims_csv"

  data_csv:
    desc: "Convert all data from xlsx to csv"
    deps:
      - noga_csv
      - ims_csv
    status:
      - test -f data/data.csv
    cmds:
      - "uv run -m noga.data data_csv"
